export const programas = [
  { description: '1', code: 'ADM_EMP', name: 'ADMÓN EMPRESAS' },
  { description: '2', code: 'ADM_TUR', name: 'ADMÓN TURÍSTICA Y HOTELERA' },
  { description: '3', code: 'COM_INT', name: 'COMERCIO INTERNACIONAL' },
  { description: '4', code: 'CON_PUB', name: 'CONTADURÍA PÚBLICA' },
  { description: '5', code: 'DER', name: 'DERECHO' },
  { description: '6', code: 'ECO', name: 'ECONOMÍA' },
  { description: '7', code: 'ENF', name: 'ENFERRMERÍA' },
  { description: '8', code: 'ING_AGRO', name: 'ING AGROINDUSTRILA' },
  { description: '9', code: 'ING_AMB', name: 'ING AMBIENTAL Y SANITARIA' },
  { description: '10', code: 'ING_ELEC', name: 'ING ELECTRÓNICA' },
  { description: '11', code: 'ING_SIS', name: 'ING SISTEMAS' },
  { description: '12', code: 'INS_QCA', name: 'INSTRUMENTACIÓN QCA' },
  { description: '13', code: 'LIC_ART', name: 'LIC ARTES' },
  { description: '14', code: 'LIC_NAT', name: 'LIC CIENCIAS NATURALES' },
  {
    description: '15',
    code: 'LIC_EFIS',
    name: 'LIC EDUCACIÓN FÍSICA, RECREACIÓN Y D',
  },
  { description: '16', code: 'LIC_ESP_ING', name: 'LIC ESPAÑOL E INLÉS' },
  {
    description: '17',
    code: 'LIC_LC_ING',
    name: 'LIC LENGUA CASTELLANA E INGLÉS',
  },
  {
    description: '18',
    code: 'LIC_LIT_LC',
    name: 'LIC LITERATURA Y LENGUA CASTELLANA',
  },
  { description: '19', code: 'LIC_MAT_FIS', name: 'LIC MATEMÁTICAS Y FÍSICA' },
  { description: '20', code: 'LIC_MAT', name: 'LIC MATEMÁTICAS' },
  { description: '21', code: 'MIC', name: 'MICROBIOLOGÍA' },
  { description: '22', code: 'MUS', name: 'MÚSICA' },
  { description: '23', code: 'PSI', name: 'PSICOLOGÍA' },
  { description: '24', code: 'SOC', name: 'SOCIOLOGÍA' },
];
