export const programas = [
  { id: 1, code: 'ADM_EMP', name: 'ADMÓN EMPRESAS' },
  { id: 2, code: 'ADM_TUR', name: 'ADMÓN TURÍSTICA Y HOTELERA' },
  { id: 3, code: 'COM_INT', name: 'COMERCIO INTERNACIONAL' },
  { id: 4, code: 'CON_PUB', name: 'CONTADURÍA PÚBLICA' },
  { id: 5, code: 'DER', name: 'DERECHO' },
  { id: 6, code: 'ECO', name: 'ECONOMÍA' },
  { id: 7, code: 'ENF', name: 'ENFERRMERÍA' },
  { id: 8, code: 'ING_AGRO', name: 'ING AGROINDUSTRILA' },
  { id: 9, code: 'ING_AMB', name: 'ING AMBIENTAL Y SANITARIA' },
  { id: 10, code: 'ING_ELEC', name: 'ING ELECTRÓNICA' },
  { id: 11, code: 'ING_SIS', name: 'ING SISTEMAS' },
  { id: 12, code: 'INS_QCA', name: 'INSTRUMENTACIÓN QCA' },
  { id: 13, code: 'LIC_ART', name: 'LIC ARTES' },
  { id: 14, code: 'LIC_NAT', name: 'LIC CIENCIAS NATURALES' },
  { id: 15, code: 'LIC_EFIS', name: 'LIC EDUCACIÓN FÍSICA, RECREACIÓN Y D' },
  { id: 16, code: 'LIC_ESP_ING', name: 'LIC ESPAÑOL E INLÉS' },
  { id: 17, code: 'LIC_LC_ING', name: 'LIC LENGUA CASTELLANA E INGLÉS' },
  { id: 18, code: 'LIC_LIT_LC', name: 'LIC LITERATURA Y LENGUA CASTELLANA' },
  { id: 19, code: 'LIC_MAT_FIS', name: 'LIC MATEMÁTICAS Y FÍSICA' },
  { id: 20, code: 'LIC_MAT', name: 'LIC MATEMÁTICAS' },
  { id: 21, code: 'MIC', name: 'MICROBIOLOGÍA' },
  { id: 22, code: 'MUS', name: 'MÚSICA' },
  { id: 23, code: 'PSI', name: 'PSICOLOGÍA' },
  { id: 24, code: 'SOC', name: 'SOCIOLOGÍA' },
];
